export const GET_MARKETS_LIST_REQUEST = 'GET_MARKETS_LIST_REQUEST';
export const GET_MARKETS_LIST_SUCCESS = 'GET_MARKETS_LIST_SUCCESS';
export const GET_MARKETS_LIST_FAILED = 'GET_MARKETS_LIST_FAILED';
