export const GET_COIN_DETAILS_REQUEST = 'GET_COIN_DETAILS_REQUEST';
export const GET_COIN_DETAILS_SUCCESS = 'GET_COIN_DETAILS_SUCCESS';
export const GET_COIN_DETAILS_FAILED = 'GET_COIN_DETAILS_FAILED';
