export const GET_COIN_DETAILS_REQUEST = 'GET_COIN_DETAILS_REQUEST';
export const GET_COIN_DETAILS_SUCCESS = 'GET_COIN_DETAILS_SUCCESS';
export const GET_COIN_DETAILS_FAILED = 'GET_COIN_DETAILS_FAILED';
export const GET_COIN_GRAPH_REQUEST = 'GET_COIN_GRAPH_REQUEST';
export const GET_COIN_GRAPH_SUCCESS = 'GET_COIN_GRAPH_SUCCESS';
export const GET_COIN_GRAPH_FAILED = 'GET_COIN_GRAPH_FAILED';
export const SET_COIN_GRAPH_DURATION = 'SET_COIN_GRAPH_DURATION';
